### PR TITLE
Add TypeScript definition

### PR DESCRIPTION
**Pull request by colinking**
This PR adds TS types to `ink-link`.

I based the typings on `ink-text-link`: https://github.com/vadimdemedes/ink-text-input

It also includes the `fallback` prop added in this PR: https://github.com/sindresorhus/ink-link/pull/5

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for creating a TypeScript definition. 🙌 Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

Some examples:
- https://github.com/sindresorhus/semver-regex/commit/039944bb5b3876913171b895488874b5c200e458
- https://github.com/sindresorhus/global-dirs/commit/0aae4d64887f77af94c4fb7ca12aa9f93c0a8291
- https://github.com/sindresorhus/md5-hex/commit/bbbfeff840f26973fbffc16d4863ae6d120079f3

**Comment by sindresorhus** [comment]
Friendly bump :)

**Comment by colinking** [comment]
Hey @sindresorhus! Finally got around to updating this to use the styleguide.

One thing: I'm not sure which React type to use on an instance of a React Component -- do you?

image

**Comment by sindresorhus** [comment]
> One thing: I'm not sure which React type to use on an instance of a React Component -- do you?

I don't. Maybe look at some other React package with a index.d.ts file and see how they do it?

**Comment by colinking** [comment]
I poked around on GitHub and found a number of folks using React + tsd, but none of them were checking the type of a React node: https://github.com/search?q=expectType+tsd+react&type=Code

From inspecting the `createElement` API, I tried `expectType<FunctionComponentElement<Props>>(<Link/>)` with no luck:

```
  index.test-d.tsx:6:0
  ✖  6:0  Parameter type FunctionComponentElement<Props> is not identical to argument type Element.
  ✖  7:0  Parameter type FunctionComponentElement<Props> is not identical to argument type Element.
  ✖  8:0  Parameter type FunctionComponentElement<Props> is not identical to argument type Element.
```

It seems like `tsd` is requesting we specifically type check against the `React.Element` type, which is not exported.

Give that, I just removed the `expectType` checks and replaced them with a simple function, since the type checks don't add a lot of value -- we already know it's valid JSX. The important thing here imo is to validate that the component properties are correct which `tsd` will do by compiling the declarations.

Does that seem good to you? :)

**Comment by sindresorhus** [comment]
> Does that seem good to you? :)

👍

**Pull request merged**
